CREATE TABLE  `ltp_transfers` (
`id` BIGINT( 12 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`client_id` BIGINT( 12 ) UNSIGNED NOT NULL ,
`clinic_id` INT( 10 ) NULL DEFAULT NULL,
`ondate` DATE NULL DEFAULT NULL
) ENGINE = MYISAM ;